vec: vec.h File Reference
vec.h File Reference
#include <stdlib.h>
Classes
struct v2
============*
vec.h *
==========================* author: samantha jane * desc: vector header file * ==========================*
struct v3
3d float vector.
struct v4
4d float vector.
struct m4
2d 4x4 homogenous matrix.
Macros
#define v2add(b)
#define v3add(b)
#define v4add(b)
#define vadd(a, b)
vector addition.
#define v2sub(b)
#define v3sub(b)
#define v4sub(b)
#define vsub(a, b)
vector subtraction.
#define v2mul(b)
#define v3mul(b)
#define v4mul(b)
#define vmul(a, b)
vector multiplication.
#define v2div(b)
#define v3div(b)
#define v4div(b)
#define vdiv(a, b)
vector division.
#define vlim(v, s)
vector limit.
#define vmag(v)
vector magnitude.
#define vscl(v, s)
vector scale.
#define v2dot(b)
#define v3dot(b)
#define v4dot(b)
#define vdot(a, b)
vector dot product.
#define vnorm(v)
vector normalize.
#define v2cross(b)
#define v3cross(b)
#define v4cross(b)
#define vcross(a, b)
vector cross product.
#define v2eq(b)
#define v3eq(b)
#define v4eq(b)
#define veq(a, b)
vector equal.
#define mxv(m, v)
matrix vector multiplication.
#define vprint(v)
print an vector to terminal.
Typedefs
typedef struct v2 v2
============*
vec.h *
==========================* author: samantha jane * desc: vector header file * ==========================*
typedef struct v3 v3
3d float vector.
typedef struct v4 v4
4d float vector.
typedef struct m4 m4
2d 4x4 homogenous matrix.
Functions
float rtod (float rad)
radians to degrees
float dtor (float deg)
degrees to radians
float flim (float x, float lim)
float limit
m4 m4proj (int w, int h, float fov, float znear, float zfar)
projection matrix (camera matrix).
m4 m4lookat (v4 pos, v4 target, v4 up)
look at/point at matrix.
m4 m4xrot (float r)
x rotation matrix.
m4 m4yrot (float r)
y rotation matrix.
m4 m4zrot (float r)
z rotation matrix.
m4 m4invxy ()
m4 m4id ()
identity matrix.
m4 m4empty ()
empty matrix.
m4 m4trans (float x, float y, float z)
translation matrix.
m4 m4invert (m4 m)
invert a matrix.
m4 m4xm4 (m4 a, m4 b)
m4 multiplication.
int m4eq (m4 a, m4 b)
void mprint (m4 m)
matrix 4 print.
v2 v2v2add (v2 a, v2 b)
vector 2 vector 2 addition.
v3 v2v3add (v2 a, v3 b)
vector 2 vector 3 addition.
v4 v2v4add (v2 a, v4 b)
vector 2 vector 4 addition.
v3 v3v2add (v3 a, v2 b)
vector 3 vector 2 addition.
v3 v3v3add (v3 a, v3 b)
vector 3 vector 3 addition.
v4 v3v4add (v3 a, v4 b)
vector 3 vector 4 addition.
v4 v4v2add (v4 a, v2 b)
vector 4 vector 2 addition.
v4 v4v3add (v4 a, v3 b)
vector 4 vector 3 addition.
v4 v4v4add (v4 a, v4 b)
vector 4 vector 4 addition.
v2 v2v2sub (v2 a, v2 b)
vector 2 vector 2 substraction.
v3 v2v3sub (v2 a, v3 b)
vector 2 vector 3 substraction.
v4 v2v4sub (v2 a, v4 b)
vector 2 vector 4 substraction.
v3 v3v2sub (v3 a, v2 b)
vector 3 vector 2 substraction.
v3 v3v3sub (v3 a, v3 b)
vector 3 vector 3 substraction.
v4 v3v4sub (v3 a, v4 b)
vector 3 vector 4 substraction.
v4 v4v2sub (v4 a, v2 b)
vector 4 vector 2 substraction.
v4 v4v3sub (v4 a, v3 b)
vector 4 vector 3 substraction.
v4 v4v4sub (v4 a, v4 b)
vector 4 vector 4 substraction.
v2 v2v2mul (v2 a, v2 b)
vector 2 vector 2 multiplication.
v3 v2v3mul (v2 a, v3 b)
vector 2 vector 3 multiplication.
v4 v2v4mul (v2 a, v4 b)
vector 2 vector 4 multiplication.
v3 v3v2mul (v3 a, v2 b)
vector 3 vector 2 multiplication.
v3 v3v3mul (v3 a, v3 b)
vector 3 vector 3 multiplication.
v4 v3v4mul (v3 a, v4 b)
vector 3 vector 4 multiplication.
v4 v4v2mul (v4 a, v2 b)
vector 4 vector 2 multiplication.
v4 v4v3mul (v4 a, v3 b)
vector 4 vector 3 multiplication.
v4 v4v4mul (v4 a, v4 b)
vector 4 vector 4 multiplication.
v2 v2v2div (v2 a, v2 b)
vector 2 vector 2 division.
v3 v2v3div (v2 a, v3 b)
vector 2 vector 3 division.
v4 v2v4div (v2 a, v4 b)
vector 2 vector 4 division.
v3 v3v2div (v3 a, v2 b)
vector 3 vector 2 division.
v3 v3v3div (v3 a, v3 b)
vector 3 vector 3 division.
v4 v3v4div (v3 a, v4 b)
vector 3 vector 3 division.
v4 v4v2div (v4 a, v2 b)
vector 4 vector 2 division.
v4 v4v3div (v4 a, v3 b)
vector 4 vector 3 division.
v4 v4v4div (v4 a, v4 b)
vector 4 vector 4 division.
v2 v2lim (v2 v, float s)
vector 2 limit.
v3 v3lim (v3 v, float s)
vector 3 limit.
v4 v4lim (v4 v, float s)
vector 4 limit.
float v2mag (v2 v)
vector 2 magnitude.
float v3mag (v3 v)
vector 3 magnitude.
float v4mag (v4 v)
vector 4 magnitude.
v2 v2scl (v2 v, float s)
vector 2 scale.
v3 v3scl (v3 v, float s)
vector 3 scale.
v4 v4scl (v4 v, float s)
vector 4 scale.
float v2v2dot (v2 a, v2 b)
vector 2 vector 2 dot product.
float v2v3dot (v2 a, v3 b)
vector 2 vector 3 dot product.
float v2v4dot (v2 a, v4 b)
vector 2 vector 4 dot product.
float v3v2dot (v3 a, v2 b)
vector 3 vector 2 dot product.
float v3v3dot (v3 a, v3 b)
vector 3 vector 3 dot product.
float v3v4dot (v3 a, v4 b)
vector 3 vector 4 dot product.
float v4v2dot (v4 a, v2 b)
vector 4 vector 2 dot product.
float v4v3dot (v4 a, v3 b)
vector 4 vector 3 dot product.
float v4v4dot (v4 a, v4 b)
vector 4 vector 4 dot product.
v2 v2norm (v2 v)
vector 2 normalize.
v3 v3norm (v3 v)
vector 3 normalize.
v4 v4norm (v4 v)
vector 4 normalize.
v4 v2v2cross (v2 a, v2 b)
vector 2 vector 2 cross product.
v4 v2v3cross (v2 a, v3 b)
vector 2 vector 3 cross product.
v4 v2v4cross (v2 a, v4 b)
vector 2 vector 4 cross product.
v4 v3v2cross (v3 a, v2 b)
vector 3 vector 2 cross product.
v4 v3v3cross (v3 a, v3 b)
vector 3 vector 3 cross product.
v4 v3v4cross (v3 a, v4 b)
vector 3 vector 4 cross product.
v4 v4v2cross (v4 a, v2 b)
vector 4 vector 2 cross product.
v4 v4v3cross (v4 a, v3 b)
vector 4 vector 3 cross product.
v4 v4v4cross (v4 a, v4 b)
vector 4 vector 4 cross product.
int v2v2eq (v2 a, v2 b)
vector 2 vector 2 equal comparison.
int v2v3eq (v2 a, v3 b)
vector 2 vector 3 equal comparison.
int v2v4eq (v2 a, v4 b)
vector 2 vector 4 equal comparison.
int v3v2eq (v3 a, v2 b)
vector 3 vector 2 equal comparison.
int v3v3eq (v3 a, v3 b)
vector 3 vector 3 equal comparison.
int v3v4eq (v3 a, v4 b)
vector 3 vector 4 equal comparison.
int v4v2eq (v4 a, v2 b)
vector 4 vector 2 equal comparison.
int v4v3eq (v4 a, v3 b)
vector 4 vector 3 equal comparison.
int v4v4eq (v4 a, v4 b)
vector 4 vector 4 equal comparison.
v4 m4xv2 (m4 m, v2 v)
v4 m4xv3 (m4 m, v3 v)
v4 m4xv4 (m4 m, v4 v)
matrix vector multiplication.
void v2print (v2 v)
vector 2 print.
void v3print (v3 v)
vector 3 print.
void v4print (v4 v)
vector 4 print.
Macro Definition Documentation
mxv
#define mxv (m, v)
Value:
  _Generic ((v), \
  v2: m4xv2, \
  v3: m4xv3, \
  v4: m4xv4 \
)(m, v)
matrix vector multiplication.
like Ax = b.
Parameters
m an m4
v an N dimensional vector
Returns
a new v4 with the matrix transform applied
Definition at line 456 of file vec.h.
v2add
#define v2add (b)
Value:
  _Generic ((b), \
  v2 : v2v2add, \
  v3 : v2v3add, \
  v4 : v2v4add  \
)
Definition at line 177 of file vec.h.
v2cross
#define v2cross (b)
Value:
  _Generic ((b), \
  v2 : v2v2cross, \
  v3 : v2v3cross, \
  v4 : v2v4cross  \
)
Definition at line 389 of file vec.h.
v2div
#define v2div (b)
Value:
  _Generic ((b), \
  v2 : v2v2div, \
  v3 : v2v3div, \
  v4 : v2v4div  \
)
Definition at line 274 of file vec.h.
v2dot
#define v2dot (b)
Value:
  _Generic ((b), \
  v2 : v2v2dot, \
  v3 : v2v3dot, \
  v4 : v2v4dot  \
)
Definition at line 346 of file vec.h.
v2eq
#define v2eq (b)
Value:
  _Generic ((b), \
  v2 : v2v2eq, \
  v3 : v2v3eq, \
  v4 : v2v4eq  \
)
Definition at line 419 of file vec.h.
v2mul
#define v2mul (b)
Value:
  _Generic ((b), \
  v2 : v2v2mul, \
  v3 : v2v3mul, \
  v4 : v2v4mul  \
)
Definition at line 243 of file vec.h.
v2sub
#define v2sub (b)
Value:
  _Generic ((b), \
  v2 : v2v2sub, \
  v3 : v2v3sub, \
  v4 : v2v4sub  \
)
Definition at line 210 of file vec.h.
v3add
#define v3add (b)
Value:
  _Generic ((b), \
  v2 : v3v2add, \
  v3 : v3v3add, \
  v4 : v3v4add  \
)
Definition at line 182 of file vec.h.
v3cross
#define v3cross (b)
Value:
  _Generic ((b), \
  v2 : v3v2cross, \
  v3 : v3v3cross, \
  v4 : v3v4cross  \
)
Definition at line 394 of file vec.h.
v3div
#define v3div (b)
Value:
  _Generic ((b), \
  v2 : v3v2div, \
  v3 : v3v3div, \
  v4 : v3v4div  \
)
Definition at line 279 of file vec.h.
v3dot
#define v3dot (b)
Value:
  _Generic ((b), \
  v2 : v3v2dot, \
  v3 : v3v3dot, \
  v4 : v3v4dot  \
)
Definition at line 351 of file vec.h.
v3eq
#define v3eq (b)
Value:
  _Generic ((b), \
  v2 : v3v2eq, \
  v3 : v3v3eq, \
  v4 : v3v4eq  \
)
Definition at line 424 of file vec.h.
v3mul
#define v3mul (b)
Value:
  _Generic ((b), \
  v2 : v3v2mul, \
  v3 : v3v3mul, \
  v4 : v3v4mul  \
)
Definition at line 248 of file vec.h.
v3sub
#define v3sub (b)
Value:
  _Generic ((b), \
  v2 : v3v2sub, \
  v3 : v3v3sub, \
  v4 : v3v4sub  \
)
Definition at line 215 of file vec.h.
v4add
#define v4add (b)
Value:
  _Generic ((b), \
  v2 : v4v2add, \
  v3 : v4v3add, \
  v4 : v4v4add  \
)
Definition at line 187 of file vec.h.
v4cross
#define v4cross (b)
Value:
  _Generic ((b), \
  v2 : v4v2cross, \
  v3 : v4v3cross, \
  v4 : v4v4cross  \
)
Definition at line 399 of file vec.h.
v4div
#define v4div (b)
Value:
  _Generic ((b), \
  v2 : v4v2div, \
  v3 : v4v3div, \
  v4 : v4v4div  \
)
Definition at line 284 of file vec.h.
v4dot
#define v4dot (b)
Value:
  _Generic ((b), \
  v2 : v4v2dot, \
  v3 : v4v3dot, \
  v4 : v4v4dot  \
)
Definition at line 356 of file vec.h.
v4eq
#define v4eq (b)
Value:
  _Generic ((b), \
  v2 : v4v2eq, \
  v3 : v4v3eq, \
  v4 : v4v4eq  \
)
Definition at line 429 of file vec.h.
v4mul
#define v4mul (b)
Value:
  _Generic ((b), \
  v2 : v4v2mul, \
  v3 : v4v3mul, \
  v4 : v4v4mul  \
)
Definition at line 253 of file vec.h.
v4sub
#define v4sub (b)
Value:
  _Generic ((b), \
  v2 : v4v2sub, \
  v3 : v4v3sub, \
  v4 : v4v4sub  \
)
Definition at line 220 of file vec.h.
vadd
#define vadd (a, b)
Value:
  _Generic ((a), \
  v2 : v2add(b), \
  v3 : v3add(b), \
  v4 : v4add(b) \
) (a, b)
vector addition.
sums a and b element wise. vectors can be different dimensions, the return vector will be of the highest dimension passed in.
Parameters
a vector
b vector
Returns
an element wise sum vector
Definition at line 203 of file vec.h.
vcross
#define vcross (a, b)
Value:
  _Generic ((a), \
  v2: v2cross(b), \
  v3: v3cross(b), \
  v4: v4cross(b)  \
) (a, b)
vector cross product.
all vectors will be promoted to v4 with zeroed .w.
Parameters
a N dimensional vector
b N dimensional vector
Returns
a v4 containing the cross product vector of a and b in r3
Definition at line 412 of file vec.h.
vdiv
#define vdiv (a, b)
Value:
  _Generic ((a), \
  v2: v2div(b), \
  v3: v3div(b), \
  v4: v4div(b)  \
) (a, b)
vector division.
divides a by b element wise. they must be the same dimensions.
Parameters
a N dimensional vector
b N dimensional vector
Returns
an N dimensional element wise product
Definition at line 298 of file vec.h.
vdot
#define vdot (a, b)
Value:
  _Generic ((a), \
  v2: v2dot(b), \
  v3: v3dot(b), \
  v4: v4dot(b)  \
) (a, b)
vector dot product.
get the dot product of vectors a and b.
Parameters
a N dimensional vector
b N dimensional vector
Returns
a scalar describing the similarity of the vectors
Definition at line 369 of file vec.h.
veq
#define veq (a, b)
Value:
  _Generic ((a), \
  v2: v2eq(b), \
  v3: v3eq(b), \
  v4: v4eq(b)  \
) (a, b)
vector equal.
promotes arguments to the same type and compares.
Parameters
a N dimensional vector
b N dimensional vector
Returns
a boolean for if a == b
Definition at line 442 of file vec.h.
vlim
#define vlim (v, s)
Value:
  _Generic ((v), \
  v2: v2lim, \
  v3: v3lim, \
  v4: v4lim  \
) (v, s)
vector limit.
limit a vector v by scalar s.
Parameters
v N dimensional vector
s N dimensional vector
Returns
v with a mangitude no greater than s
Definition at line 312 of file vec.h.
vmag
#define vmag (v)
Value:
  _Generic ((v), \
  v2: v2mag, \
  v3: v3mag, \
  v4: v4mag  \
) (v)
vector magnitude.
get the scalar magnitude of vector v.
Parameters
v N dimensional vector
Returns
the magnitude of v
Definition at line 325 of file vec.h.
vmul
#define vmul (a, b)
Value:
  _Generic ((a), \
  v2: v2mul(b), \
  v3: v3mul(b), \
  v4: v4mul(b)  \
) (a, b)
vector multiplication.
multiplies a and b element wise. they must be the same dimensions.
Parameters
a N dimensional vector
b N dimensional vector
Returns
an N dimensional element wise product
Definition at line 267 of file vec.h.
vnorm
#define vnorm (v)
Value:
  _Generic ((v), \
  v2: v2norm, \
  v3: v3norm, \
  v4: v4norm  \
) (v)
vector normalize.
normalize the vector v by dividing its elements by its magnitude.
Parameters
v N dimensional vector
Returns
a normalized v
Definition at line 382 of file vec.h.
vprint
#define vprint (v)
Value:
  _Generic ((v), \
  v2: v2print, \
  v3: v3print, \
  v4: v4print  \
) (v)
print an vector to terminal.
Parameters
v N dimensional vector
Returns
void
Definition at line 468 of file vec.h.
vscl
#define vscl (v, s)
Value:
  _Generic ((v), \
  v2: v2scl, \
  v3: v3scl, \
  v4: v4scl  \
) (v, s)
vector scale.
multiply the magnitude of vector v by scalar s.
Parameters
v N dimensional vector
v N dimensional vector
Returns
the magnitude of v
Definition at line 339 of file vec.h.
vsub
#define vsub (a, b)
Value:
  _Generic ((a), \
  v2: v2sub(b), \
  v3: v3sub(b), \
  v4: v4sub(b)  \
) (a, b)
vector subtraction.
subtracts b from a element wise. vectors can be different dimensions, the return vector will be of the highest dimension passed in.
Parameters
a vector
b vector
Returns
an element wise difference vector
Definition at line 236 of file vec.h.
Typedef Documentation
m4
typedef struct m4 m4
2d 4x4 homogenous matrix.
v2
typedef struct v2 v2
============*
vec.h *
==========================* author: samantha jane * desc: vector header file * ==========================*
2d float vector.
v3
typedef struct v3 v3
3d float vector.
v4
typedef struct v4 v4
4d float vector.
Function Documentation
dtor()
float dtor (float deg)
degrees to radians
Definition at line 26 of file vec.c.
References PI.
flim()
float flim (float x, float lim)
float limit
Definition at line 31 of file vec.c.
m4empty()
m4 m4empty ()
empty matrix.
Returns
a matrix of all zeros
Definition at line 1416 of file vec.c.
m4eq()
int m4eq (m4 a, m4 b)
m4id()
m4 m4id ()
identity matrix.
Returns
a 4x4 identity matrix.
Definition at line 1430 of file vec.c.
m4invert()
m4 m4invert (m4 m)
invert a matrix.
Parameters
m an m4 to invert
Returns
Definition at line 1523 of file vec.c.
References m4::m.
m4invxy()
m4 m4invxy ()
m4lookat()
m4 m4lookat (v4 pos, v4 target, v4 up)
look at/point at matrix.
create the necessary transform to rotate towards a position in space.
Parameters
pos
target
up
Returns
m4 with rotation transform
Definition at line 1638 of file vec.c.
References v4norm(), v4scl(), v4v4cross(), v4v4dot(), v4v4sub(), v4::x, v4::y, and v4::z.
m4proj()
m4 m4proj (int w, int h, float fovd, float znear, float zfar)
projection matrix (camera matrix).
Parameters
w the width of the screen in pixels
h the hieght of the screen in pixels
fovd field of view in degrees (not radians!)
znear near clipping plane
zfar far clipping plane
Returns
projection matrix that converts from world to screen coordinates
Definition at line 1616 of file vec.c.
References dtor().
m4trans()
m4 m4trans (float x, float y, float z)
translation matrix.
trans rights :)
Parameters
x translation in x dimension
y translation in y dimension
z translation in z dimension
Returns
a 4x4 translation matrix for 3d space
Definition at line 1463 of file vec.c.
m4xm4()
m4 m4xm4 (m4 m1, m4 m2)
m4 multiplication.
multiply two 4x4 homogenous matrices.
Parameters
m1 m4
m2 m4
Returns
m4 resulting from m1 right multiplied by m2
Definition at line 1556 of file vec.c.
References m4::m.
m4xrot()
m4 m4xrot (float r)
x rotation matrix.
Parameters
r rotation in radians
Returns
a rotation matrix
Definition at line 1478 of file vec.c.
m4xv2()
v4 m4xv2 (m4 m, v2 v)
Definition at line 1601 of file vec.c.
References m4xv4(), v2::x, and v2::y.
m4xv3()
v4 m4xv3 (m4 m, v3 v)
Definition at line 1597 of file vec.c.
References m4xv4(), v3::x, v3::y, and v3::z.
m4xv4()
v4 m4xv4 (m4 m, v4 v)
matrix vector multiplication.
transform v by matrix m through right multiplication.
Parameters
m m4
Definition at line 1574 of file vec.c.
References m4::m, v4::w, v4::x, v4::y, and v4::z.
m4yrot()
m4 m4yrot (float r)
y rotation matrix.
Parameters
r rotation in radians
Returns
a rotation matrix
Definition at line 1493 of file vec.c.
m4zrot()
m4 m4zrot (float r)
z rotation matrix.
Parameters
r rotation in radians
Returns
a rotation matrix
Definition at line 1508 of file vec.c.
mprint()
void mprint (m4 m)
matrix 4 print.
Parameters
m m4
Returns
void
Definition at line 1688 of file vec.c.
References m4::m.
rtod()
float rtod (float rad)
radians to degrees
Definition at line 21 of file vec.c.
References PI.
v2lim()
v2 v2lim (v2 v, float s)
vector 2 limit.
limits the magnitude of v to s.
Parameters
v v2
s float
Returns
v2 v with magnitude of at most s.
Definition at line 794 of file vec.c.
References fminf(), v2mag(), and v2scl().
v2mag()
float v2mag (v2 v)
vector 2 magnitude.
get the length of the vector v.
Parameters
v v2
Returns
float
Definition at line 702 of file vec.c.
References v2::x, and v2::y.
v2norm()
v2 v2norm (v2 v)
vector 2 normalize.
return its input but divided by its own length.
Parameters
v v2
Returns
v2 v / v.len
Definition at line 1003 of file vec.c.
References vmag, v2::x, and v2::y.
v2print()
void v2print (v2 v)
vector 2 print.
Parameters
v v2
Returns
void
Definition at line 1658 of file vec.c.
References v2::x, and v2::y.
v2scl()
v2 v2scl (v2 v, float s)
vector 2 scale.
scale the vector v by s.
Parameters
v v2
s float
Returns
v2 v * s
Definition at line 744 of file vec.c.
References v2::x, and v2::y.
v2v2add()
v2 v2v2add (v2 a, v2 b)
vector 2 vector 2 addition.
elementwise sum of a and b.
Parameters
a v2
b v2
Returns
v2 a + b
Definition at line 49 of file vec.c.
References v2::x, and v2::y.
v2v2cross()
v4 v2v2cross (v2 a, v2 b)
vector 2 vector 2 cross product.
calculate the norm from a and b. note return promotion to v4, .w = 0.
Parameters
a v2
b v2
Returns
v4 a x b
Definition at line 1098 of file vec.c.
References v4v4cross(), v2::x, v4::x, and v2::y.
v2v2div()
v2 v2v2div (v2 a, v2 b)
vector 2 vector 2 division.
elementwise quotient of a and b.
Parameters
a v2
b v2
Returns
v2 a / b
Definition at line 539 of file vec.c.
References v2::x, and v2::y.
v2v2dot()
float v2v2dot (v2 a, v2 b)
vector 2 vector 2 dot product.
return a scalar describing the similarity of a and b.
Parameters
a v2
b v2
Returns
float a . b
Definition at line 839 of file vec.c.
References v2::x, and v2::y.
v2v2eq()
int v2v2eq (v2 a, v2 b)
vector 2 vector 2 equal comparison.
check of contents of a and b are identical.
Parameters
a v2
b v2
Returns
boolean
Definition at line 1245 of file vec.c.
References v2::x, and v2::y.
v2v2mul()
v2 v2v2mul (v2 a, v2 b)
vector 2 vector 2 multiplication.
elementwise product of a and b.
Parameters
a v2
b v2
Returns
v2 a * b
Definition at line 375 of file vec.c.
References v2::x, and v2::y.
v2v2sub()
v2 v2v2sub (v2 a, v2 b)
vector 2 vector 2 substraction.
elementwise difference of a and b.
Parameters
a v2
b v2
Returns
v2 a - b
Definition at line 211 of file vec.c.
References v2::x, and v2::y.
v2v3add()
v3 v2v3add (v2 a, v3 b)
vector 2 vector 3 addition.
elementwise sum of a and b. a promoted before summation.
Parameters
a v2
b v3
Returns
v3 a + b
Definition at line 98 of file vec.c.
References v3v3add(), v2::x, v3::x, and v2::y.
v2v3cross()
v4 v2v3cross (v2 a, v3 b)
vector 2 vector 3 cross product.
calculate the norm from a and b. a promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v2
b v3
Returns
v4 a x b
Definition at line 1202 of file vec.c.
References v3v3cross(), v2::x, v3::x, and v2::y.
v2v3div()
v3 v2v3div (v2 a, v3 b)
vector 2 vector 3 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v2
b v3
Returns
v3 a / b
Definition at line 590 of file vec.c.
References v3v3div(), v2::x, v3::x, and v2::y.
v2v3dot()
float v2v3dot (v2 a, v3 b)
vector 2 vector 3 dot product.
return a scalar describing the similarity of a and b. a promoted before computation.
Parameters
a v2
b v3
Returns
float a . b
Definition at line 890 of file vec.c.
References v3v3dot(), v2::x, v3::x, and v2::y.
v2v3eq()
int v2v3eq (v2 a, v3 b)
vector 2 vector 3 equal comparison.
promotes a then checks if contents of a and b are identical.
Parameters
a v2
b v3
Returns
boolean
Definition at line 1295 of file vec.c.
References v3v3eq(), v2::x, v3::x, and v2::y.
v2v3mul()
v3 v2v3mul (v2 a, v3 b)
vector 2 vector 3 multiplication.
elementwise product of a and b. a promoted before multiplication.
Parameters
a v2
b v3
Returns
v3 a * b
Definition at line 426 of file vec.c.
References v3v3mul(), v2::x, v3::x, and v2::y.
v2v3sub()
v3 v2v3sub (v2 a, v3 b)
vector 2 vector 3 substraction.
elementwise difference of a and b. a promoted before subtraction.
Parameters
a v2
b v3
Returns
v3 a - b
Definition at line 262 of file vec.c.
References v3v3sub(), v2::x, v3::x, and v2::y.
v2v4add()
v4 v2v4add (v2 a, v4 b)
vector 2 vector 4 addition.
elementwise sum of a and b. a promoted before summation.
Parameters
a v2
b v4
Returns
v4 a + b
Definition at line 116 of file vec.c.
References v4v4add(), v2::x, v4::x, and v2::y.
v2v4cross()
v4 v2v4cross (v2 a, v4 b)
vector 2 vector 4 cross product.
calculate the norm from a and b. a promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v2
b v4
Returns
v4 a x b
Definition at line 1221 of file vec.c.
References v3v3cross(), v2::x, v3::x, v4::x, v2::y, v4::y, and v4::z.
v2v4div()
v4 v2v4div (v2 a, v4 b)
vector 2 vector 4 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v2
b v4
Returns
v4 a / b
Definition at line 608 of file vec.c.
References v4v4div(), v2::x, v4::x, and v2::y.
v2v4dot()
float v2v4dot (v2 a, v4 b)
vector 2 vector 4 dot product.
return a scalar describing the similarity of a and b. a promoted before computation.
Parameters
a v2
b v4
Returns
float a . b
Definition at line 908 of file vec.c.
References v4v4dot(), v2::x, v4::x, and v2::y.
v2v4eq()
int v2v4eq (v2 a, v4 b)
vector 2 vector 4 equal comparison.
promotes a then checks if contents of a and b are identical.
Parameters
a v2
b v4
Returns
boolean
Definition at line 1312 of file vec.c.
References v4v4eq(), v2::x, v4::x, and v2::y.
v2v4mul()
v4 v2v4mul (v2 a, v4 b)
vector 2 vector 4 multiplication.
elementwise product of a and b. a promoted before multiplication.
Parameters
a v2
b v4
Returns
v4 a * b
Definition at line 444 of file vec.c.
References v4v4mul(), v2::x, v4::x, and v2::y.
v2v4sub()
v4 v2v4sub (v2 a, v4 b)
vector 2 vector 4 substraction.
elementwise difference of a and b. a promoted before subtraction.
Parameters
a v2
b v4
Returns
v4 a - b
Definition at line 280 of file vec.c.
References v4v4sub(), v2::x, v4::x, and v2::y.
v3lim()
v3 v3lim (v3 v, float s)
vector 3 limit.
limits the magnitude of v to s.
Parameters
v v3
s float
Returns
v3 v with magnitude of at most s.
Definition at line 808 of file vec.c.
References fminf(), v3mag(), and v3scl().
v3mag()
float v3mag (v3 v)
vector 3 magnitude.
get the length of the vector v.
Parameters
v v3
Returns
float
Definition at line 715 of file vec.c.
References v3::x, v3::y, and v3::z.
v3norm()
v3 v3norm (v3 v)
vector 3 normalize.
return its input but divided by its own length.
Parameters
v v3
Returns
v3 v / v.len
Definition at line 1018 of file vec.c.
References vmag, v3::x, v3::y, and v3::z.
v3print()
void v3print (v3 v)
vector 3 print.
Parameters
v v3
Returns
void
Definition at line 1668 of file vec.c.
References v3::x, v3::y, and v3::z.
v3scl()
v3 v3scl (v3 v, float s)
vector 3 scale.
scale the vector v by s.
Parameters
v v3
s float
Returns
v3 v * s
Definition at line 759 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v2add()
v3 v3v2add (v3 a, v2 b)
vector 3 vector 2 addition.
elementwise sum of a and b. b promoted before summation.
Parameters
a v3
b v2
Returns
v3 a + b
Definition at line 135 of file vec.c.
References v3v3add(), v2::x, v3::x, and v2::y.
v3v2cross()
v4 v3v2cross (v3 a, v2 b)
vector 3 vector 2 cross product.
calculate the norm from a and b. b promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v3
b v2
Returns
v4 a x b
Definition at line 1164 of file vec.c.
References v3v3cross(), v2::x, v3::x, and v2::y.
v3v2div()
v3 v3v2div (v3 a, v2 b)
vector 3 vector 2 division.
elementwise quotient of a and b. b promoted before division.
Parameters
a v3
b v2
Returns
v3 a / b
Definition at line 627 of file vec.c.
References v3v3div(), v2::x, v3::x, and v2::y.
v3v2dot()
float v3v2dot (v3 a, v2 b)
vector 3 vector 2 dot product.
return a scalar describing the similarity of a and b. b promoted before computation.
Parameters
a v3
b v2
Returns
float a . b
Definition at line 927 of file vec.c.
References v3v3dot(), v2::x, v3::x, and v2::y.
v3v2eq()
int v3v2eq (v3 a, v2 b)
vector 3 vector 2 equal comparison.
promotes b then checks if contents of a and b are identical.
Parameters
a v3
b v2
Returns
boolean
Definition at line 1330 of file vec.c.
References v3v3eq(), v2::x, v3::x, and v2::y.
v3v2mul()
v3 v3v2mul (v3 a, v2 b)
vector 3 vector 2 multiplication.
elementwise product of a and b. b promoted before multiplication.
Parameters
a v3
b v2
Returns
v3 a * b
Definition at line 463 of file vec.c.
References v3v3mul(), v2::x, v3::x, and v2::y.
v3v2sub()
v3 v3v2sub (v3 a, v2 b)
vector 3 vector 2 substraction.
elementwise difference of a and b. b promoted before subtraction.
Parameters
a v3
b v2
Returns
v3 a - b
Definition at line 299 of file vec.c.
References v3v3sub(), v2::x, v3::x, and v2::y.
v3v3add()
v3 v3v3add (v3 a, v3 b)
vector 3 vector 3 addition.
elementwise sum of a and b.
Parameters
a v3
b v3
Returns
v3 a + b
Definition at line 63 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3cross()
v4 v3v3cross (v3 a, v3 b)
vector 3 vector 3 cross product.
calculate the norm from a and b. note output promotion, .w = 0.
Parameters
a v3
b v3
Returns
v4 a x b
Definition at line 1073 of file vec.c.
References v4v4cross(), v3::x, v4::x, v3::y, and v3::z.
v3v3div()
v3 v3v3div (v3 a, v3 b)
vector 3 vector 3 division.
elementwise quotient of a and b.
Parameters
a v3
b v3
Returns
v3 a / b
Definition at line 554 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3dot()
float v3v3dot (v3 a, v3 b)
vector 3 vector 3 dot product.
return a scalar describing the similarity of a and b.
Parameters
a v3
b v3
Returns
float a . b
Definition at line 854 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3eq()
int v3v3eq (v3 a, v3 b)
vector 3 vector 3 equal comparison.
check of contents of a and b are identical.
Parameters
a v3
b v3
Returns
boolean
Definition at line 1260 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3mul()
v3 v3v3mul (v3 a, v3 b)
vector 3 vector 3 multiplication.
elementwise product of a and b.
Parameters
a v3
b v3
Returns
v3 a * b
Definition at line 390 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3sub()
v3 v3v3sub (v3 a, v3 b)
vector 3 vector 3 substraction.
elementwise difference of a and b.
Parameters
a v3
b v3
Returns
v3 a - b
Definition at line 226 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v4add()
v4 v3v4add (v3 a, v4 b)
vector 3 vector 4 addition.
elementwise sum of a and b. a promoted before summation.
Parameters
a v3
b v4
Returns
v4 a + b
Definition at line 153 of file vec.c.
References v4v4add(), v3::x, v4::x, v3::y, and v3::z.
v3v4cross()
v4 v3v4cross (v3 a, v4 b)
vector 3 vector 4 cross product.
calculate the norm from a and b. a promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v3
b v4
Returns
v4 a x b
Definition at line 1183 of file vec.c.
References v3v3cross(), v3::x, v4::x, v4::y, and v4::z.
v3v4div()
v4 v3v4div (v3 a, v4 b)
vector 3 vector 3 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v3
b v4
Returns
v4 a / b
Definition at line 645 of file vec.c.
References v4v4div(), v3::x, v4::x, v3::y, and v3::z.
v3v4dot()
float v3v4dot (v3 a, v4 b)
vector 3 vector 4 dot product.
return a scalar describing the similarity of a and b. a promoted before computation.
Parameters
a v3
b v4
Returns
float a . b
Definition at line 945 of file vec.c.
References v4v4dot(), v3::x, v4::x, v3::y, and v3::z.
v3v4eq()
int v3v4eq (v3 a, v4 b)
vector 3 vector 4 equal comparison.
promotes a then checks if contents of a and b are identical.
Parameters
a v3
b v4
Returns
boolean
Definition at line 1347 of file vec.c.
References v4v4eq(), v3::x, v4::x, v3::y, and v3::z.
v3v4mul()
v4 v3v4mul (v3 a, v4 b)
vector 3 vector 4 multiplication.
elementwise product of a and b. a promoted before multiplication.
Parameters
a v3
b v4
Returns
v4 a * b
Definition at line 481 of file vec.c.
References v4v4mul(), v3::x, v4::x, v3::y, and v3::z.
v3v4sub()
v4 v3v4sub (v3 a, v4 b)
vector 3 vector 4 substraction.
elementwise difference of a and b. a promoted before subtraction.
Parameters
a v3
b v4
Returns
v4 a - b
Definition at line 317 of file vec.c.
References v4v4sub(), v3::x, v4::x, v3::y, and v3::z.
v4lim()
v4 v4lim (v4 v, float s)
vector 4 limit.
limits the magnitude of v to s.
Parameters
v v4
s float
Returns
v4 v with magnitude of at most s.
Definition at line 822 of file vec.c.
References fminf(), v4mag(), and v4scl().
v4mag()
float v4mag (v4 v)
vector 4 magnitude.
get the length of the vector v.
Parameters
v v4
Returns
float
Definition at line 728 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4norm()
v4 v4norm (v4 v)
vector 4 normalize.
return its input but divided by its own length.
Parameters
v v4
Returns
v4 v / v.len
Definition at line 1034 of file vec.c.
References vmag, v4::w, v4::x, v4::y, and v4::z.
v4print()
void v4print (v4 v)
vector 4 print.
Parameters
v v4
Returns
void
Definition at line 1678 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4scl()
v4 v4scl (v4 v, float s)
vector 4 scale.
scale the vector v by s.
Parameters
v v4
s float
Returns
v4 v * s
Definition at line 775 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v2add()
v4 v4v2add (v4 a, v2 b)
vector 4 vector 2 addition.
elementwise sum of a and b. b promoted before summation.
Parameters
a v4
b v2
Returns
v4 a + b
Definition at line 172 of file vec.c.
References v4v4add(), v2::x, v4::x, and v2::y.
v4v2cross()
v4 v4v2cross (v4 a, v2 b)
vector 4 vector 2 cross product.
calculate the norm from a and b. b promoted before cross.
Parameters
a v4
b v2
Returns
v4 a x b
Definition at line 1125 of file vec.c.
References v4v4cross(), v2::x, v4::x, and v2::y.
v4v2div()
v4 v4v2div (v4 a, v2 b)
vector 4 vector 2 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v4
b v2
Returns
v4 a / b
Definition at line 664 of file vec.c.
References v4v4div(), v2::x, v4::x, and v2::y.
v4v2dot()
float v4v2dot (v4 a, v2 b)
vector 4 vector 2 dot product.
return a scalar describing the similarity of a and b. b promoted before computation.
Parameters
a v4
b v2
Returns
float a . b
Definition at line 964 of file vec.c.
References v4v4dot(), v2::x, v4::x, and v2::y.
v4v2eq()
int v4v2eq (v4 a, v2 b)
vector 4 vector 2 equal comparison.
promotes b then checks if contents of a and b are identical.
Parameters
a v4
b v2
Returns
boolean
Definition at line 1365 of file vec.c.
References v4v4eq(), v2::x, v4::x, and v2::y.
v4v2mul()
v4 v4v2mul (v4 a, v2 b)
vector 4 vector 2 multiplication.
elementwise product of a and b. b promoted before multiplication.
Parameters
a v4
b v2
Returns
v4 a * b
Definition at line 500 of file vec.c.
References v4v4mul(), v2::x, v4::x, and v2::y.
v4v2sub()
v4 v4v2sub (v4 a, v2 b)
vector 4 vector 2 substraction.
elementwise difference of a and b. b promoted before subtraction.
Parameters
a v4
b v2
Returns
v4 a - b
Definition at line 336 of file vec.c.
References v4v4sub(), v2::x, v4::x, and v2::y.
v4v3add()
v4 v4v3add (v4 a, v3 b)
vector 4 vector 3 addition.
elementwise sum of a and b. b promoted before summation.
Parameters
a v4
b v3
Returns
v4 a + b
Definition at line 191 of file vec.c.
References v4v4add(), v3::x, v4::x, and v3::y.
v4v3cross()
v4 v4v3cross (v4 a, v3 b)
vector 4 vector 3 cross product.
calculate the norm from a and b. b promoted before cross.
Parameters
a v4
b v3
Returns
v4 a x b
Definition at line 1144 of file vec.c.
References v4v4cross(), v3::x, v4::x, v3::y, and v3::z.
v4v3div()
v4 v4v3div (v4 a, v3 b)
vector 4 vector 3 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v4
b v3
Returns
v4 a / b
Definition at line 683 of file vec.c.
References v4v4div(), v3::x, v4::x, v3::y, and v3::z.
v4v3dot()
float v4v3dot (v4 a, v3 b)
vector 4 vector 3 dot product.
return a scalar describing the similarity of a and b. b promoted before computation.
Parameters
a v4
b v3
Returns
float a . b
Definition at line 983 of file vec.c.
References v4v4dot(), v3::x, v4::x, v3::y, and v3::z.
v4v3eq()
int v4v3eq (v4 a, v3 b)
vector 4 vector 3 equal comparison.
promotes b then checks if contents of a and b are identical.
Parameters
a v4
b v3
Returns
boolean
Definition at line 1383 of file vec.c.
References v4v4eq(), v3::x, v4::x, v3::y, and v3::z.
v4v3mul()
v4 v4v3mul (v4 a, v3 b)
vector 4 vector 3 multiplication.
elementwise product of a and b. b promoted before multiplication.
Parameters
a v4
b v3
Returns
v4 a * b
Definition at line 519 of file vec.c.
References v4v4mul(), v3::x, v4::x, v3::y, and v3::z.
v4v3sub()
v4 v4v3sub (v4 a, v3 b)
vector 4 vector 3 substraction.
elementwise difference of a and b. b promoted before subtraction.
Parameters
a v4
b v3
Returns
v4 a - b
Definition at line 355 of file vec.c.
References v4v4sub(), v3::x, v4::x, v3::y, and v3::z.
v4v4add()
v4 v4v4add (v4 a, v4 b)
vector 4 vector 4 addition.
elementwise sum of a and b.
Parameters
a v4
b v4
Returns
v4 a + b
Definition at line 78 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4cross()
v4 v4v4cross (v4 a, v4 b)
vector 4 vector 4 cross product.
calculate the norm from a and b.
Parameters
a v4
b v4
Returns
v4 a x b
Definition at line 1055 of file vec.c.
References v4::x, v4::y, and v4::z.
v4v4div()
v4 v4v4div (v4 a, v4 b)
vector 4 vector 4 division.
elementwise quotient of a and b.
Parameters
a v4
b v4
Returns
v4 a / b
Definition at line 570 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4dot()
float v4v4dot (v4 a, v4 b)
vector 4 vector 4 dot product.
return a scalar describing the similarity of a and b.
Parameters
a v4
b v4
Returns
float a . b
Definition at line 870 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4eq()
int v4v4eq (v4 a, v4 b)
vector 4 vector 4 equal comparison.
check if contents of a and b are identical.
Parameters
a v4
b v4
Returns
boolean
Definition at line 1276 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4mul()
v4 v4v4mul (v4 a, v4 b)
vector 4 vector 4 multiplication.
elementwise product of a and b.
Parameters
a v4
b v4
Returns
v4 a * b
Definition at line 406 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4sub()
v4 v4v4sub (v4 a, v4 b)
vector 4 vector 4 substraction.
elementwise difference of a and b.
Parameters
a v4
b v4
Returns
v4 a - b
Definition at line 242 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.