vec: vec.c File Reference
vec.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "vec.h"
Macros
#define PI 3.1415926535
Functions
float rtod (float rad)
radians to degrees
float dtor (float deg)
degrees to radians
float flim (float x, float lim)
float limit
float fminf (float, float)
v2 v2v2add (v2 a, v2 b)
vector 2 vector 2 addition.
v3 v3v3add (v3 a, v3 b)
vector 3 vector 3 addition.
v4 v4v4add (v4 a, v4 b)
vector 4 vector 4 addition.
v3 v2v3add (v2 a, v3 b)
vector 2 vector 3 addition.
v4 v2v4add (v2 a, v4 b)
vector 2 vector 4 addition.
v3 v3v2add (v3 a, v2 b)
vector 3 vector 2 addition.
v4 v3v4add (v3 a, v4 b)
vector 3 vector 4 addition.
v4 v4v2add (v4 a, v2 b)
vector 4 vector 2 addition.
v4 v4v3add (v4 a, v3 b)
vector 4 vector 3 addition.
v2 v2v2sub (v2 a, v2 b)
vector 2 vector 2 substraction.
v3 v3v3sub (v3 a, v3 b)
vector 3 vector 3 substraction.
v4 v4v4sub (v4 a, v4 b)
vector 4 vector 4 substraction.
v3 v2v3sub (v2 a, v3 b)
vector 2 vector 3 substraction.
v4 v2v4sub (v2 a, v4 b)
vector 2 vector 4 substraction.
v3 v3v2sub (v3 a, v2 b)
vector 3 vector 2 substraction.
v4 v3v4sub (v3 a, v4 b)
vector 3 vector 4 substraction.
v4 v4v2sub (v4 a, v2 b)
vector 4 vector 2 substraction.
v4 v4v3sub (v4 a, v3 b)
vector 4 vector 3 substraction.
v2 v2v2mul (v2 a, v2 b)
vector 2 vector 2 multiplication.
v3 v3v3mul (v3 a, v3 b)
vector 3 vector 3 multiplication.
v4 v4v4mul (v4 a, v4 b)
vector 4 vector 4 multiplication.
v3 v2v3mul (v2 a, v3 b)
vector 2 vector 3 multiplication.
v4 v2v4mul (v2 a, v4 b)
vector 2 vector 4 multiplication.
v3 v3v2mul (v3 a, v2 b)
vector 3 vector 2 multiplication.
v4 v3v4mul (v3 a, v4 b)
vector 3 vector 4 multiplication.
v4 v4v2mul (v4 a, v2 b)
vector 4 vector 2 multiplication.
v4 v4v3mul (v4 a, v3 b)
vector 4 vector 3 multiplication.
v2 v2v2div (v2 a, v2 b)
vector 2 vector 2 division.
v3 v3v3div (v3 a, v3 b)
vector 3 vector 3 division.
v4 v4v4div (v4 a, v4 b)
vector 4 vector 4 division.
v3 v2v3div (v2 a, v3 b)
vector 2 vector 3 division.
v4 v2v4div (v2 a, v4 b)
vector 2 vector 4 division.
v3 v3v2div (v3 a, v2 b)
vector 3 vector 2 division.
v4 v3v4div (v3 a, v4 b)
vector 3 vector 3 division.
v4 v4v2div (v4 a, v2 b)
vector 4 vector 2 division.
v4 v4v3div (v4 a, v3 b)
vector 4 vector 3 division.
float v2mag (v2 v)
vector 2 magnitude.
float v3mag (v3 v)
vector 3 magnitude.
float v4mag (v4 v)
vector 4 magnitude.
v2 v2scl (v2 v, float s)
vector 2 scale.
v3 v3scl (v3 v, float s)
vector 3 scale.
v4 v4scl (v4 v, float s)
vector 4 scale.
v2 v2lim (v2 v, float s)
vector 2 limit.
v3 v3lim (v3 v, float s)
vector 3 limit.
v4 v4lim (v4 v, float s)
vector 4 limit.
float v2v2dot (v2 a, v2 b)
vector 2 vector 2 dot product.
float v3v3dot (v3 a, v3 b)
vector 3 vector 3 dot product.
float v4v4dot (v4 a, v4 b)
vector 4 vector 4 dot product.
float v2v3dot (v2 a, v3 b)
vector 2 vector 3 dot product.
float v2v4dot (v2 a, v4 b)
vector 2 vector 4 dot product.
float v3v2dot (v3 a, v2 b)
vector 3 vector 2 dot product.
float v3v4dot (v3 a, v4 b)
vector 3 vector 4 dot product.
float v4v2dot (v4 a, v2 b)
vector 4 vector 2 dot product.
float v4v3dot (v4 a, v3 b)
vector 4 vector 3 dot product.
v2 v2norm (v2 v)
vector 2 normalize.
v3 v3norm (v3 v)
vector 3 normalize.
v4 v4norm (v4 v)
vector 4 normalize.
v4 v4v4cross (v4 a, v4 b)
vector 4 vector 4 cross product.
v4 v3v3cross (v3 a, v3 b)
vector 3 vector 3 cross product.
v4 v2v2cross (v2 a, v2 b)
vector 2 vector 2 cross product.
v4 v4v2cross (v4 a, v2 b)
vector 4 vector 2 cross product.
v4 v4v3cross (v4 a, v3 b)
vector 4 vector 3 cross product.
v4 v3v2cross (v3 a, v2 b)
vector 3 vector 2 cross product.
v4 v3v4cross (v3 a, v4 b)
vector 3 vector 4 cross product.
v4 v2v3cross (v2 a, v3 b)
vector 2 vector 3 cross product.
v4 v2v4cross (v2 a, v4 b)
vector 2 vector 4 cross product.
int v2v2eq (v2 a, v2 b)
vector 2 vector 2 equal comparison.
int v3v3eq (v3 a, v3 b)
vector 3 vector 3 equal comparison.
int v4v4eq (v4 a, v4 b)
vector 4 vector 4 equal comparison.
int v2v3eq (v2 a, v3 b)
vector 2 vector 3 equal comparison.
int v2v4eq (v2 a, v4 b)
vector 2 vector 4 equal comparison.
int v3v2eq (v3 a, v2 b)
vector 3 vector 2 equal comparison.
int v3v4eq (v3 a, v4 b)
vector 3 vector 4 equal comparison.
int v4v2eq (v4 a, v2 b)
vector 4 vector 2 equal comparison.
int v4v3eq (v4 a, v3 b)
vector 4 vector 3 equal comparison.
int meq (m4 a, m4 b)
matrix equal.
m4 m4empty ()
empty matrix.
m4 m4id ()
identity matrix.
m4 m4invxyid ()
inverse x and y id matrix
m4 m4trans (float x, float y, float z)
translation matrix.
m4 m4xrot (float r)
x rotation matrix.
m4 m4yrot (float r)
y rotation matrix.
m4 m4zrot (float r)
z rotation matrix.
m4 m4invert (m4 m)
invert a matrix.
m4 m4xm4 (m4 m1, m4 m2)
m4 multiplication.
v4 m4xv4 (m4 m, v4 v)
matrix vector multiplication.
v4 m4xv3 (m4 m, v3 v)
v4 m4xv2 (m4 m, v2 v)
m4 m4proj (int w, int h, float fovd, float znear, float zfar)
projection matrix (camera matrix).
m4 m4lookat (v4 pos, v4 target, v4 up)
look at/point at matrix.
void v2print (v2 v)
vector 2 print.
void v3print (v3 v)
vector 3 print.
void v4print (v4 v)
vector 4 print.
void mprint (m4 m)
matrix 4 print.
Macro Definition Documentation
PI
#define PI 3.1415926535
Definition at line 16 of file vec.c.
Function Documentation
dtor()
float dtor (float deg)
degrees to radians
Definition at line 26 of file vec.c.
References PI.
flim()
float flim (float x, float lim)
float limit
Definition at line 31 of file vec.c.
fminf()
float fminf (float , float)
m4empty()
m4 m4empty ()
empty matrix.
Returns
a matrix of all zeros
Definition at line 1416 of file vec.c.
m4id()
m4 m4id ()
identity matrix.
Returns
a 4x4 identity matrix.
Definition at line 1430 of file vec.c.
m4invert()
m4 m4invert (m4 m)
invert a matrix.
Parameters
m an m4 to invert
Returns
Definition at line 1523 of file vec.c.
References m4::m.
m4invxyid()
m4 m4invxyid ()
inverse x and y id matrix
Returns
the identity matrix with a -1 in x and y pivot
Definition at line 1444 of file vec.c.
m4lookat()
m4 m4lookat (v4 pos, v4 target, v4 up)
look at/point at matrix.
create the necessary transform to rotate towards a position in space.
Parameters
pos
target
up
Returns
m4 with rotation transform
Definition at line 1638 of file vec.c.
References v4norm(), v4scl(), v4v4cross(), v4v4dot(), v4v4sub(), v4::x, v4::y, and v4::z.
m4proj()
m4 m4proj (int w, int h, float fovd, float znear, float zfar)
projection matrix (camera matrix).
Parameters
w the width of the screen in pixels
h the hieght of the screen in pixels
fovd field of view in degrees (not radians!)
znear near clipping plane
zfar far clipping plane
Returns
projection matrix that converts from world to screen coordinates
Definition at line 1616 of file vec.c.
References dtor().
m4trans()
m4 m4trans (float x, float y, float z)
translation matrix.
trans rights :)
Parameters
x translation in x dimension
y translation in y dimension
z translation in z dimension
Returns
a 4x4 translation matrix for 3d space
Definition at line 1463 of file vec.c.
m4xm4()
m4 m4xm4 (m4 m1, m4 m2)
m4 multiplication.
multiply two 4x4 homogenous matrices.
Parameters
m1 m4
m2 m4
Returns
m4 resulting from m1 right multiplied by m2
Definition at line 1556 of file vec.c.
References m4::m.
m4xrot()
m4 m4xrot (float r)
x rotation matrix.
Parameters
r rotation in radians
Returns
a rotation matrix
Definition at line 1478 of file vec.c.
m4xv2()
v4 m4xv2 (m4 m, v2 v)
Definition at line 1601 of file vec.c.
References m4xv4(), v2::x, and v2::y.
m4xv3()
v4 m4xv3 (m4 m, v3 v)
Definition at line 1597 of file vec.c.
References m4xv4(), v3::x, v3::y, and v3::z.
m4xv4()
v4 m4xv4 (m4 m, v4 v)
matrix vector multiplication.
transform v by matrix m through right multiplication.
Parameters
m m4
Definition at line 1574 of file vec.c.
References m4::m, v4::w, v4::x, v4::y, and v4::z.
m4yrot()
m4 m4yrot (float r)
y rotation matrix.
Parameters
r rotation in radians
Returns
a rotation matrix
Definition at line 1493 of file vec.c.
m4zrot()
m4 m4zrot (float r)
z rotation matrix.
Parameters
r rotation in radians
Returns
a rotation matrix
Definition at line 1508 of file vec.c.
meq()
int meq (m4 a, m4 b)
matrix equal.
Parameters
a an m4
b another m4
Returns
a boolean for if the matrices a == b.
Definition at line 1402 of file vec.c.
References m4::m.
mprint()
void mprint (m4 m)
matrix 4 print.
Parameters
m m4
Returns
void
Definition at line 1688 of file vec.c.
References m4::m.
rtod()
float rtod (float rad)
radians to degrees
Definition at line 21 of file vec.c.
References PI.
v2lim()
v2 v2lim (v2 v, float s)
vector 2 limit.
limits the magnitude of v to s.
Parameters
v v2
s float
Returns
v2 v with magnitude of at most s.
Definition at line 794 of file vec.c.
References fminf(), v2mag(), and v2scl().
v2mag()
float v2mag (v2 v)
vector 2 magnitude.
get the length of the vector v.
Parameters
v v2
Returns
float
Definition at line 702 of file vec.c.
References v2::x, and v2::y.
v2norm()
v2 v2norm (v2 v)
vector 2 normalize.
return its input but divided by its own length.
Parameters
v v2
Returns
v2 v / v.len
Definition at line 1003 of file vec.c.
References vmag, v2::x, and v2::y.
v2print()
void v2print (v2 v)
vector 2 print.
Parameters
v v2
Returns
void
Definition at line 1658 of file vec.c.
References v2::x, and v2::y.
v2scl()
v2 v2scl (v2 v, float s)
vector 2 scale.
scale the vector v by s.
Parameters
v v2
s float
Returns
v2 v * s
Definition at line 744 of file vec.c.
References v2::x, and v2::y.
v2v2add()
v2 v2v2add (v2 a, v2 b)
vector 2 vector 2 addition.
elementwise sum of a and b.
Parameters
a v2
b v2
Returns
v2 a + b
Definition at line 49 of file vec.c.
References v2::x, and v2::y.
v2v2cross()
v4 v2v2cross (v2 a, v2 b)
vector 2 vector 2 cross product.
calculate the norm from a and b. note return promotion to v4, .w = 0.
Parameters
a v2
b v2
Returns
v4 a x b
Definition at line 1098 of file vec.c.
References v4v4cross(), v2::x, v4::x, and v2::y.
v2v2div()
v2 v2v2div (v2 a, v2 b)
vector 2 vector 2 division.
elementwise quotient of a and b.
Parameters
a v2
b v2
Returns
v2 a / b
Definition at line 539 of file vec.c.
References v2::x, and v2::y.
v2v2dot()
float v2v2dot (v2 a, v2 b)
vector 2 vector 2 dot product.
return a scalar describing the similarity of a and b.
Parameters
a v2
b v2
Returns
float a . b
Definition at line 839 of file vec.c.
References v2::x, and v2::y.
v2v2eq()
int v2v2eq (v2 a, v2 b)
vector 2 vector 2 equal comparison.
check of contents of a and b are identical.
Parameters
a v2
b v2
Returns
boolean
Definition at line 1245 of file vec.c.
References v2::x, and v2::y.
v2v2mul()
v2 v2v2mul (v2 a, v2 b)
vector 2 vector 2 multiplication.
elementwise product of a and b.
Parameters
a v2
b v2
Returns
v2 a * b
Definition at line 375 of file vec.c.
References v2::x, and v2::y.
v2v2sub()
v2 v2v2sub (v2 a, v2 b)
vector 2 vector 2 substraction.
elementwise difference of a and b.
Parameters
a v2
b v2
Returns
v2 a - b
Definition at line 211 of file vec.c.
References v2::x, and v2::y.
v2v3add()
v3 v2v3add (v2 a, v3 b)
vector 2 vector 3 addition.
elementwise sum of a and b. a promoted before summation.
Parameters
a v2
b v3
Returns
v3 a + b
Definition at line 98 of file vec.c.
References v3v3add(), v2::x, v3::x, and v2::y.
v2v3cross()
v4 v2v3cross (v2 a, v3 b)
vector 2 vector 3 cross product.
calculate the norm from a and b. a promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v2
b v3
Returns
v4 a x b
Definition at line 1202 of file vec.c.
References v3v3cross(), v2::x, v3::x, and v2::y.
v2v3div()
v3 v2v3div (v2 a, v3 b)
vector 2 vector 3 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v2
b v3
Returns
v3 a / b
Definition at line 590 of file vec.c.
References v3v3div(), v2::x, v3::x, and v2::y.
v2v3dot()
float v2v3dot (v2 a, v3 b)
vector 2 vector 3 dot product.
return a scalar describing the similarity of a and b. a promoted before computation.
Parameters
a v2
b v3
Returns
float a . b
Definition at line 890 of file vec.c.
References v3v3dot(), v2::x, v3::x, and v2::y.
v2v3eq()
int v2v3eq (v2 a, v3 b)
vector 2 vector 3 equal comparison.
promotes a then checks if contents of a and b are identical.
Parameters
a v2
b v3
Returns
boolean
Definition at line 1295 of file vec.c.
References v3v3eq(), v2::x, v3::x, and v2::y.
v2v3mul()
v3 v2v3mul (v2 a, v3 b)
vector 2 vector 3 multiplication.
elementwise product of a and b. a promoted before multiplication.
Parameters
a v2
b v3
Returns
v3 a * b
Definition at line 426 of file vec.c.
References v3v3mul(), v2::x, v3::x, and v2::y.
v2v3sub()
v3 v2v3sub (v2 a, v3 b)
vector 2 vector 3 substraction.
elementwise difference of a and b. a promoted before subtraction.
Parameters
a v2
b v3
Returns
v3 a - b
Definition at line 262 of file vec.c.
References v3v3sub(), v2::x, v3::x, and v2::y.
v2v4add()
v4 v2v4add (v2 a, v4 b)
vector 2 vector 4 addition.
elementwise sum of a and b. a promoted before summation.
Parameters
a v2
b v4
Returns
v4 a + b
Definition at line 116 of file vec.c.
References v4v4add(), v2::x, v4::x, and v2::y.
v2v4cross()
v4 v2v4cross (v2 a, v4 b)
vector 2 vector 4 cross product.
calculate the norm from a and b. a promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v2
b v4
Returns
v4 a x b
Definition at line 1221 of file vec.c.
References v3v3cross(), v2::x, v3::x, v4::x, v2::y, v4::y, and v4::z.
v2v4div()
v4 v2v4div (v2 a, v4 b)
vector 2 vector 4 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v2
b v4
Returns
v4 a / b
Definition at line 608 of file vec.c.
References v4v4div(), v2::x, v4::x, and v2::y.
v2v4dot()
float v2v4dot (v2 a, v4 b)
vector 2 vector 4 dot product.
return a scalar describing the similarity of a and b. a promoted before computation.
Parameters
a v2
b v4
Returns
float a . b
Definition at line 908 of file vec.c.
References v4v4dot(), v2::x, v4::x, and v2::y.
v2v4eq()
int v2v4eq (v2 a, v4 b)
vector 2 vector 4 equal comparison.
promotes a then checks if contents of a and b are identical.
Parameters
a v2
b v4
Returns
boolean
Definition at line 1312 of file vec.c.
References v4v4eq(), v2::x, v4::x, and v2::y.
v2v4mul()
v4 v2v4mul (v2 a, v4 b)
vector 2 vector 4 multiplication.
elementwise product of a and b. a promoted before multiplication.
Parameters
a v2
b v4
Returns
v4 a * b
Definition at line 444 of file vec.c.
References v4v4mul(), v2::x, v4::x, and v2::y.
v2v4sub()
v4 v2v4sub (v2 a, v4 b)
vector 2 vector 4 substraction.
elementwise difference of a and b. a promoted before subtraction.
Parameters
a v2
b v4
Returns
v4 a - b
Definition at line 280 of file vec.c.
References v4v4sub(), v2::x, v4::x, and v2::y.
v3lim()
v3 v3lim (v3 v, float s)
vector 3 limit.
limits the magnitude of v to s.
Parameters
v v3
s float
Returns
v3 v with magnitude of at most s.
Definition at line 808 of file vec.c.
References fminf(), v3mag(), and v3scl().
v3mag()
float v3mag (v3 v)
vector 3 magnitude.
get the length of the vector v.
Parameters
v v3
Returns
float
Definition at line 715 of file vec.c.
References v3::x, v3::y, and v3::z.
v3norm()
v3 v3norm (v3 v)
vector 3 normalize.
return its input but divided by its own length.
Parameters
v v3
Returns
v3 v / v.len
Definition at line 1018 of file vec.c.
References vmag, v3::x, v3::y, and v3::z.
v3print()
void v3print (v3 v)
vector 3 print.
Parameters
v v3
Returns
void
Definition at line 1668 of file vec.c.
References v3::x, v3::y, and v3::z.
v3scl()
v3 v3scl (v3 v, float s)
vector 3 scale.
scale the vector v by s.
Parameters
v v3
s float
Returns
v3 v * s
Definition at line 759 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v2add()
v3 v3v2add (v3 a, v2 b)
vector 3 vector 2 addition.
elementwise sum of a and b. b promoted before summation.
Parameters
a v3
b v2
Returns
v3 a + b
Definition at line 135 of file vec.c.
References v3v3add(), v2::x, v3::x, and v2::y.
v3v2cross()
v4 v3v2cross (v3 a, v2 b)
vector 3 vector 2 cross product.
calculate the norm from a and b. b promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v3
b v2
Returns
v4 a x b
Definition at line 1164 of file vec.c.
References v3v3cross(), v2::x, v3::x, and v2::y.
v3v2div()
v3 v3v2div (v3 a, v2 b)
vector 3 vector 2 division.
elementwise quotient of a and b. b promoted before division.
Parameters
a v3
b v2
Returns
v3 a / b
Definition at line 627 of file vec.c.
References v3v3div(), v2::x, v3::x, and v2::y.
v3v2dot()
float v3v2dot (v3 a, v2 b)
vector 3 vector 2 dot product.
return a scalar describing the similarity of a and b. b promoted before computation.
Parameters
a v3
b v2
Returns
float a . b
Definition at line 927 of file vec.c.
References v3v3dot(), v2::x, v3::x, and v2::y.
v3v2eq()
int v3v2eq (v3 a, v2 b)
vector 3 vector 2 equal comparison.
promotes b then checks if contents of a and b are identical.
Parameters
a v3
b v2
Returns
boolean
Definition at line 1330 of file vec.c.
References v3v3eq(), v2::x, v3::x, and v2::y.
v3v2mul()
v3 v3v2mul (v3 a, v2 b)
vector 3 vector 2 multiplication.
elementwise product of a and b. b promoted before multiplication.
Parameters
a v3
b v2
Returns
v3 a * b
Definition at line 463 of file vec.c.
References v3v3mul(), v2::x, v3::x, and v2::y.
v3v2sub()
v3 v3v2sub (v3 a, v2 b)
vector 3 vector 2 substraction.
elementwise difference of a and b. b promoted before subtraction.
Parameters
a v3
b v2
Returns
v3 a - b
Definition at line 299 of file vec.c.
References v3v3sub(), v2::x, v3::x, and v2::y.
v3v3add()
v3 v3v3add (v3 a, v3 b)
vector 3 vector 3 addition.
elementwise sum of a and b.
Parameters
a v3
b v3
Returns
v3 a + b
Definition at line 63 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3cross()
v4 v3v3cross (v3 a, v3 b)
vector 3 vector 3 cross product.
calculate the norm from a and b. note output promotion, .w = 0.
Parameters
a v3
b v3
Returns
v4 a x b
Definition at line 1073 of file vec.c.
References v4v4cross(), v3::x, v4::x, v3::y, and v3::z.
v3v3div()
v3 v3v3div (v3 a, v3 b)
vector 3 vector 3 division.
elementwise quotient of a and b.
Parameters
a v3
b v3
Returns
v3 a / b
Definition at line 554 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3dot()
float v3v3dot (v3 a, v3 b)
vector 3 vector 3 dot product.
return a scalar describing the similarity of a and b.
Parameters
a v3
b v3
Returns
float a . b
Definition at line 854 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3eq()
int v3v3eq (v3 a, v3 b)
vector 3 vector 3 equal comparison.
check of contents of a and b are identical.
Parameters
a v3
b v3
Returns
boolean
Definition at line 1260 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3mul()
v3 v3v3mul (v3 a, v3 b)
vector 3 vector 3 multiplication.
elementwise product of a and b.
Parameters
a v3
b v3
Returns
v3 a * b
Definition at line 390 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v3sub()
v3 v3v3sub (v3 a, v3 b)
vector 3 vector 3 substraction.
elementwise difference of a and b.
Parameters
a v3
b v3
Returns
v3 a - b
Definition at line 226 of file vec.c.
References v3::x, v3::y, and v3::z.
v3v4add()
v4 v3v4add (v3 a, v4 b)
vector 3 vector 4 addition.
elementwise sum of a and b. a promoted before summation.
Parameters
a v3
b v4
Returns
v4 a + b
Definition at line 153 of file vec.c.
References v4v4add(), v3::x, v4::x, v3::y, and v3::z.
v3v4cross()
v4 v3v4cross (v3 a, v4 b)
vector 3 vector 4 cross product.
calculate the norm from a and b. a promoted before cross. note return promotion to v4, .w = 0.
Parameters
a v3
b v4
Returns
v4 a x b
Definition at line 1183 of file vec.c.
References v3v3cross(), v3::x, v4::x, v4::y, and v4::z.
v3v4div()
v4 v3v4div (v3 a, v4 b)
vector 3 vector 3 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v3
b v4
Returns
v4 a / b
Definition at line 645 of file vec.c.
References v4v4div(), v3::x, v4::x, v3::y, and v3::z.
v3v4dot()
float v3v4dot (v3 a, v4 b)
vector 3 vector 4 dot product.
return a scalar describing the similarity of a and b. a promoted before computation.
Parameters
a v3
b v4
Returns
float a . b
Definition at line 945 of file vec.c.
References v4v4dot(), v3::x, v4::x, v3::y, and v3::z.
v3v4eq()
int v3v4eq (v3 a, v4 b)
vector 3 vector 4 equal comparison.
promotes a then checks if contents of a and b are identical.
Parameters
a v3
b v4
Returns
boolean
Definition at line 1347 of file vec.c.
References v4v4eq(), v3::x, v4::x, v3::y, and v3::z.
v3v4mul()
v4 v3v4mul (v3 a, v4 b)
vector 3 vector 4 multiplication.
elementwise product of a and b. a promoted before multiplication.
Parameters
a v3
b v4
Returns
v4 a * b
Definition at line 481 of file vec.c.
References v4v4mul(), v3::x, v4::x, v3::y, and v3::z.
v3v4sub()
v4 v3v4sub (v3 a, v4 b)
vector 3 vector 4 substraction.
elementwise difference of a and b. a promoted before subtraction.
Parameters
a v3
b v4
Returns
v4 a - b
Definition at line 317 of file vec.c.
References v4v4sub(), v3::x, v4::x, v3::y, and v3::z.
v4lim()
v4 v4lim (v4 v, float s)
vector 4 limit.
limits the magnitude of v to s.
Parameters
v v4
s float
Returns
v4 v with magnitude of at most s.
Definition at line 822 of file vec.c.
References fminf(), v4mag(), and v4scl().
v4mag()
float v4mag (v4 v)
vector 4 magnitude.
get the length of the vector v.
Parameters
v v4
Returns
float
Definition at line 728 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4norm()
v4 v4norm (v4 v)
vector 4 normalize.
return its input but divided by its own length.
Parameters
v v4
Returns
v4 v / v.len
Definition at line 1034 of file vec.c.
References vmag, v4::w, v4::x, v4::y, and v4::z.
v4print()
void v4print (v4 v)
vector 4 print.
Parameters
v v4
Returns
void
Definition at line 1678 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4scl()
v4 v4scl (v4 v, float s)
vector 4 scale.
scale the vector v by s.
Parameters
v v4
s float
Returns
v4 v * s
Definition at line 775 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v2add()
v4 v4v2add (v4 a, v2 b)
vector 4 vector 2 addition.
elementwise sum of a and b. b promoted before summation.
Parameters
a v4
b v2
Returns
v4 a + b
Definition at line 172 of file vec.c.
References v4v4add(), v2::x, v4::x, and v2::y.
v4v2cross()
v4 v4v2cross (v4 a, v2 b)
vector 4 vector 2 cross product.
calculate the norm from a and b. b promoted before cross.
Parameters
a v4
b v2
Returns
v4 a x b
Definition at line 1125 of file vec.c.
References v4v4cross(), v2::x, v4::x, and v2::y.
v4v2div()
v4 v4v2div (v4 a, v2 b)
vector 4 vector 2 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v4
b v2
Returns
v4 a / b
Definition at line 664 of file vec.c.
References v4v4div(), v2::x, v4::x, and v2::y.
v4v2dot()
float v4v2dot (v4 a, v2 b)
vector 4 vector 2 dot product.
return a scalar describing the similarity of a and b. b promoted before computation.
Parameters
a v4
b v2
Returns
float a . b
Definition at line 964 of file vec.c.
References v4v4dot(), v2::x, v4::x, and v2::y.
v4v2eq()
int v4v2eq (v4 a, v2 b)
vector 4 vector 2 equal comparison.
promotes b then checks if contents of a and b are identical.
Parameters
a v4
b v2
Returns
boolean
Definition at line 1365 of file vec.c.
References v4v4eq(), v2::x, v4::x, and v2::y.
v4v2mul()
v4 v4v2mul (v4 a, v2 b)
vector 4 vector 2 multiplication.
elementwise product of a and b. b promoted before multiplication.
Parameters
a v4
b v2
Returns
v4 a * b
Definition at line 500 of file vec.c.
References v4v4mul(), v2::x, v4::x, and v2::y.
v4v2sub()
v4 v4v2sub (v4 a, v2 b)
vector 4 vector 2 substraction.
elementwise difference of a and b. b promoted before subtraction.
Parameters
a v4
b v2
Returns
v4 a - b
Definition at line 336 of file vec.c.
References v4v4sub(), v2::x, v4::x, and v2::y.
v4v3add()
v4 v4v3add (v4 a, v3 b)
vector 4 vector 3 addition.
elementwise sum of a and b. b promoted before summation.
Parameters
a v4
b v3
Returns
v4 a + b
Definition at line 191 of file vec.c.
References v4v4add(), v3::x, v4::x, and v3::y.
v4v3cross()
v4 v4v3cross (v4 a, v3 b)
vector 4 vector 3 cross product.
calculate the norm from a and b. b promoted before cross.
Parameters
a v4
b v3
Returns
v4 a x b
Definition at line 1144 of file vec.c.
References v4v4cross(), v3::x, v4::x, v3::y, and v3::z.
v4v3div()
v4 v4v3div (v4 a, v3 b)
vector 4 vector 3 division.
elementwise quotient of a and b. a promoted before division.
Parameters
a v4
b v3
Returns
v4 a / b
Definition at line 683 of file vec.c.
References v4v4div(), v3::x, v4::x, v3::y, and v3::z.
v4v3dot()
float v4v3dot (v4 a, v3 b)
vector 4 vector 3 dot product.
return a scalar describing the similarity of a and b. b promoted before computation.
Parameters
a v4
b v3
Returns
float a . b
Definition at line 983 of file vec.c.
References v4v4dot(), v3::x, v4::x, v3::y, and v3::z.
v4v3eq()
int v4v3eq (v4 a, v3 b)
vector 4 vector 3 equal comparison.
promotes b then checks if contents of a and b are identical.
Parameters
a v4
b v3
Returns
boolean
Definition at line 1383 of file vec.c.
References v4v4eq(), v3::x, v4::x, v3::y, and v3::z.
v4v3mul()
v4 v4v3mul (v4 a, v3 b)
vector 4 vector 3 multiplication.
elementwise product of a and b. b promoted before multiplication.
Parameters
a v4
b v3
Returns
v4 a * b
Definition at line 519 of file vec.c.
References v4v4mul(), v3::x, v4::x, v3::y, and v3::z.
v4v3sub()
v4 v4v3sub (v4 a, v3 b)
vector 4 vector 3 substraction.
elementwise difference of a and b. b promoted before subtraction.
Parameters
a v4
b v3
Returns
v4 a - b
Definition at line 355 of file vec.c.
References v4v4sub(), v3::x, v4::x, v3::y, and v3::z.
v4v4add()
v4 v4v4add (v4 a, v4 b)
vector 4 vector 4 addition.
elementwise sum of a and b.
Parameters
a v4
b v4
Returns
v4 a + b
Definition at line 78 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4cross()
v4 v4v4cross (v4 a, v4 b)
vector 4 vector 4 cross product.
calculate the norm from a and b.
Parameters
a v4
b v4
Returns
v4 a x b
Definition at line 1055 of file vec.c.
References v4::x, v4::y, and v4::z.
v4v4div()
v4 v4v4div (v4 a, v4 b)
vector 4 vector 4 division.
elementwise quotient of a and b.
Parameters
a v4
b v4
Returns
v4 a / b
Definition at line 570 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4dot()
float v4v4dot (v4 a, v4 b)
vector 4 vector 4 dot product.
return a scalar describing the similarity of a and b.
Parameters
a v4
b v4
Returns
float a . b
Definition at line 870 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4eq()
int v4v4eq (v4 a, v4 b)
vector 4 vector 4 equal comparison.
check if contents of a and b are identical.
Parameters
a v4
b v4
Returns
boolean
Definition at line 1276 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4mul()
v4 v4v4mul (v4 a, v4 b)
vector 4 vector 4 multiplication.
elementwise product of a and b.
Parameters
a v4
b v4
Returns
v4 a * b
Definition at line 406 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.
v4v4sub()
v4 v4v4sub (v4 a, v4 b)
vector 4 vector 4 substraction.
elementwise difference of a and b.
Parameters
a v4
b v4
Returns
v4 a - b
Definition at line 242 of file vec.c.
References v4::w, v4::x, v4::y, and v4::z.